# Generated by Django 3.0.6 on 2020-05-10 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_auto_20200510_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Object', models.CharField(max_length=500, unique=True, verbose_name='Наименование объекта')),
                ('Adress_Object', models.TextField(unique=True, verbose_name='Адрес')),
                ('NCH_General', models.SmallIntegerField(verbose_name='Н/Ч общее')),
                ('NCH_Spent', models.SmallIntegerField(verbose_name='Н/Ч затрачено')),
                ('Perform_proc', models.SmallIntegerField(default=0, verbose_name='Выполнено')),
                ('ID_Ingener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Инженер', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
                ('ID_Menedger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Менеджер', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('ID_Montazhnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Старший_монтажник', to=settings.AUTH_USER_MODEL, verbose_name='Старший_монтажник')),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
                ('ID_Rukovoditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Руководитель', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
