# Generated by Django 3.0.6 on 2020-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='NCH_Spent',
            field=models.SmallIntegerField(default=0, verbose_name='Н/Ч затрачено'),
        ),
    ]
