# Generated by Django 3.0.6 on 2020-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_object_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
