# Generated by Django 3.0.6 on 2020-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_auto_20200512_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='FIO_zakazchika',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='ФИО заказчика'),
        ),
        migrations.AddField(
            model_name='object',
            name='Number_phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер телефона заказчика'),
        ),
    ]
