# Generated by Django 3.0.6 on 2020-05-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_auto_20200517_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='Number_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона заказчика'),
        ),
    ]
