# Generated by Django 3.0.6 on 2020-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_auto_20200517_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='FIO_zakazchika',
            field=models.CharField(blank=True, max_length=500, verbose_name='ФИО заказчика'),
        ),
    ]
