# Generated by Django 3.0.6 on 2020-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0008_auto_20200517_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='Note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
