# Generated by Django 3.0.6 on 2020-05-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0010_auto_20200525_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='ID_Ingener',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Инженер', to=settings.AUTH_USER_MODEL, verbose_name='Инженер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='ID_Menedger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Менеджер', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='ID_Montazhnik',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Старший_монтажник', to=settings.AUTH_USER_MODEL, verbose_name='Старший_монтажник'),
        ),
        migrations.AlterField(
            model_name='object',
            name='ID_Rukovoditel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Руководитель', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
