# Generated by Django 3.0.6 on 2020-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0012_auto_20200525_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='NCH_Left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Н/Ч осталось'),
        ),
    ]
