# Generated by Django 3.0.6 on 2020-08-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0016_auto_20200811_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
