# Generated by Django 3.0.6 on 2020-08-19 12:50
import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0017_auto_20200811_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 11, 1, 7, 15, 12, 655838, tzinfo=utc), verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='senior',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ответственный'),
        ),
    ]
