# Generated by Django 3.0.6 on 2020-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0019_auto_20200819_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
