# Generated by Django 3.0.6 on 2020-08-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0020_auto_20200819_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='date',
        ),
    ]
