# Generated by Django 3.0.6 on 2020-08-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0025_auto_20200802_1321'),
        ('object', '0013_object_nch_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование материала')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Unit', verbose_name='Ед. измерения')),
            ],
            options={
                'verbose_name': 'Материалы',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Колличество (планируемое)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Materials', verbose_name='Материал')),
                ('name_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object.Object', verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Планируемые материалы',
                'verbose_name_plural': 'Планируемые материалы',
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='DeliveredMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Колличество (планируемое)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Materials', verbose_name='Материал')),
                ('name_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object.Object', verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Поставленные материалы',
                'verbose_name_plural': 'Поставленные материалы',
                'ordering': ['material'],
            },
        ),
    ]
