# Generated by Django 3.0.6 on 2020-08-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Группа материалов и работ')),
            ],
            options={
                'verbose_name': 'Группа материалов и работ',
                'verbose_name_plural': 'Группы материалов и работ',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='planmaterials',
            old_name='quantity',
            new_name='quantity_plan',
        ),
        migrations.AddField(
            model_name='planmaterials',
            name='quantity_delivered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Колличество (поставленное)'),
        ),
        migrations.AddField(
            model_name='planmaterials',
            name='name_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materials.Groups', verbose_name='Название группы'),
            preserve_default=False,
        ),
    ]
