# Generated by Django 3.0.6 on 2020-08-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_delete_deliveredmaterials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmaterials',
            old_name='name_group',
            new_name='group',
        ),
    ]
