# Generated by Django 3.0.6 on 2020-08-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_auto_20200805_1316'),
        ('materials', '0006_auto_20200805_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmaterials',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Groups', verbose_name='Название группы'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
