# Generated by Django 3.0.6 on 2020-08-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_materials_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='group',
        ),
    ]
