# Generated by Django 3.0.6 on 2020-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_remove_materials_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmaterials',
            name='group',
        ),
        migrations.AddField(
            model_name='materials',
            name='articul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='materials',
            name='code_of_product',
            field=models.CharField(blank=True, max_length=500, verbose_name='Код продукта'),
        ),
        migrations.AddField(
            model_name='materials',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Производитель'),
        ),
    ]
