# Generated by Django 3.0.6 on 2020-08-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_auto_20200805_1316'),
        ('materials', '0011_auto_20200819_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='articul',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='code_of_product',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Код продукта'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Unit', verbose_name='Ед. измерения'),
        ),
    ]
