# Generated by Django 3.0.6 on 2020-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_auto_20200819_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='articul',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='code_of_product',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Код продукта'),
        ),
    ]
