# Generated by Django 3.0.6 on 2020-05-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200511_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completeworks',
            options={'ordering': ['name_object'], 'verbose_name': 'Выполненные работы', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.AlterModelOptions(
            name='planworks',
            options={'ordering': ['name_object'], 'verbose_name': 'Планируемые работы', 'verbose_name_plural': 'Планируемые работы'},
        ),
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'ordering': ['name'], 'verbose_name': 'Вид работы', 'verbose_name_plural': 'Вид работ'},
        ),
        migrations.AddField(
            model_name='completeworks',
            name='plan_work',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='work.PlanWorks', verbose_name='Планируемые работы'),
            preserve_default=False,
        ),
    ]
