# Generated by Django 3.0.6 on 2020-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200511_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeworks',
            name='plan_work',
        ),
    ]
