# Generated by Django 3.0.6 on 2020-05-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_auto_20200511_1621'),
        ('work', '0004_remove_completeworks_plan_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_plan', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Колличество(планируемое)')),
                ('quantity_complete', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Колличество(выполнено)')),
                ('NCH_general', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Н/Ч за вид работ (на партию)')),
                ('NCH_left', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Н/Ч за вид работ (осталось)')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('data', models.DateField(verbose_name='Дата выполнения')),
                ('perform_proc', models.SmallIntegerField(default=0, verbose_name='Выполнено')),
                ('name_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object.Object', verbose_name='Название объекта')),
                ('type_works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.TypeOfWork', verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Планируемые работы',
                'verbose_name_plural': 'Планируемые работы',
                'ordering': ['name_object'],
            },
        ),
        migrations.RemoveField(
            model_name='planworks',
            name='name_object',
        ),
        migrations.RemoveField(
            model_name='planworks',
            name='type_works',
        ),
        migrations.DeleteModel(
            name='CompleteWorks',
        ),
        migrations.DeleteModel(
            name='PlanWorks',
        ),
    ]
