# Generated by Django 3.0.6 on 2020-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200511_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['-data'], 'verbose_name': 'Работы (планируемые и выполненные)', 'verbose_name_plural': 'Работы (планируемые и выполненные)'},
        ),
        migrations.AlterField(
            model_name='works',
            name='quantity_complete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Колличество (выполнено)'),
        ),
        migrations.AlterField(
            model_name='works',
            name='quantity_plan',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Колличество (планируемое)'),
        ),
    ]
