# Generated by Django 3.0.6 on 2020-05-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20200522_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeworks',
            old_name='quantity',
            new_name='quantity_complete',
        ),
    ]
