# Generated by Django 3.0.6 on 2020-05-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20200523_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeworks',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='planworks',
            name='unit',
        ),
    ]
