# Generated by Django 3.0.6 on 2020-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20200523_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planworks',
            name='NCH_ed_vrem',
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='NCH_ed_vrem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Н/Ч за вид работ (единица времени)'),
        ),
    ]
