# Generated by Django 3.0.6 on 2020-05-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20200523_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofwork',
            name='NCH_ed_vrem',
        ),
    ]
