# Generated by Django 3.0.6 on 2020-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_remove_typeofwork_nch_ed_vrem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planworks',
            name='NCH_general',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Н/Ч за вид работ (общее)'),
        ),
        migrations.AlterField(
            model_name='planworks',
            name='quantity_plan',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Колличество (планируемое)'),
        ),
    ]
