# Generated by Django 3.0.6 on 2020-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20200526_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeworks',
            name='senior',
            field=models.CharField(default=2, max_length=300, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completeworks',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
