# Generated by Django 3.0.6 on 2020-06-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_auto_20200613_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completeworks',
            options={'ordering': ['-date', '-NCH_spent'], 'verbose_name': 'Выполненные работы', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.AddField(
            model_name='completeworks',
            name='plan',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='work.PlanWorks', verbose_name='Планируемые работы'),
            preserve_default=False,
        ),
    ]
