# Generated by Django 3.0.6 on 2020-07-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_completeworks_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planworks',
            name='NCH_left',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Н/Ч за вид работ (осталось)'),
            preserve_default=False,
        ),
    ]
