# Generated by Django 3.0.6 on 2020-07-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_planworks_nch_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planworks',
            old_name='NCH_left',
            new_name='perform_proc',
        ),
    ]
