# Generated by Django 3.0.6 on 2020-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20200709_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planworks',
            name='perform_proc',
            field=models.SmallIntegerField(default=0, verbose_name='Н/Ч за вид работ (осталось)'),
        ),
    ]
