# Generated by Django 3.0.6 on 2020-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_auto_20200709_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeworks',
            name='last_add_info',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, verbose_name='Последнее добавление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planworks',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Процент в окрасе(от красного до зеленого)'),
        ),
    ]
