# Generated by Django 3.0.6 on 2020-07-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_auto_20200709_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='planworks',
            name='NCH_left',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Н/Ч за вид работ (осталось)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planworks',
            name='NCH_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Н/Ч за вид работ (затрачено)'),
        ),
        migrations.AddField(
            model_name='planworks',
            name='quantity_complete',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Колличество (выполнено)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planworks',
            name='perform_proc',
            field=models.SmallIntegerField(default=0, verbose_name='Выполнено'),
        ),
    ]
