# Generated by Django 3.0.6 on 2020-07-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_auto_20200710_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeworks',
            name='last_add_info',
        ),
    ]
