# Generated by Django 3.0.6 on 2020-08-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_auto_20200802_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Группа материалов и работ')),
            ],
            options={
                'verbose_name': 'Группа материалов и работ',
                'verbose_name_plural': 'Группы материалов и работ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='work.Groups', verbose_name='Название группы'),
            preserve_default=False,
        ),
    ]
