# Generated by Django 3.0.6 on 2020-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='Name_Position',
            field=models.CharField(max_length=50, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Name_Project',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
