# Generated by Django 3.0.6 on 2020-08-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ID_Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Position', to='project.Position', verbose_name='Должность'),
        ),
    ]
