# Generated by Django 3.0.6 on 2020-08-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200806_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ID_Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_Position', to='project.Position', verbose_name='Должность'),
        ),
    ]
