# Generated by Django 3.0.6 on 2020-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200806_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
