# Generated by Django 3.0.6 on 2020-08-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200806_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фото'),
        ),
    ]
