# Generated by Django 3.0.6 on 2020-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
